casevo/accounts/urls.py
from django.conf.urls import patterns, url

from casevo.accounts.views import AccountUpdateView, AccountListView


urlpatterns = patterns('',
    url(r'^$', AccountListView.as_view(), name='list'),
    url(r'^(?P<pk>[\d]+)/$', AccountUpdateView.as_view(), name='update'),
)

casevo/statistics/urls.py
from django.conf.urls import patterns, url

from casevo.statistics.views import StatisticHomeView, StatisticAccountsPieView


urlpatterns = patterns('',
    url(r'^$', StatisticHomeView.as_view(), name='home'),
    url(r'^accounts/pie/$', StatisticAccountsPieView.as_view(), name='accounts-pie'),
)

casevo/transactions/urls.py
from django.conf.urls import patterns, url

from casevo.transactions.views import TransactionListView


urlpatterns = patterns('',
    url(r'^$', TransactionListView.as_view(), name='list'),
)

casevo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from casevo.common.views import CasevoHomeView


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', CasevoHomeView.as_view(), name='home'),

    url(r'^accounts/', include('casevo.accounts.urls', namespace='accounts')),
    url(r'^transactions/', include('casevo.transactions.urls', namespace='transactions')),
    url(r'^statistics/', include('casevo.statistics.urls', namespace='statistics')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

casevo/accounts/models.py
from django.db import models

from currencies.models import Currency


class Account(models.Model):
    identifier = models.CharField(max_length=255)
    number = models.CharField(max_length=100)
    blz = models.CharField(max_length=100)
    currency = models.ForeignKey(Currency, default=0)

    class Meta:
        unique_together = [('number', 'blz')]

    def __unicode__(self):
        return u'%s' % (self.identifier)

    def balance(self):
        return sum([k['value'] for k in self.transactions_in.values('value')]) - sum([k['value'] for k in self.transactions_out.values('value')])

casevo/statistics/models.py
from django.db import models

# Create your models here.

casevo/transactions/models.py
from django.db import models

from casevo.accounts.models import Account


class Transaction(models.Model):
    date = models.DateField()
    source = models.ForeignKey(Account, related_name='transactions_out')
    target = models.ForeignKey(Account, related_name='transactions_in')
    value = models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
    description = models.TextField()

    class Meta:
        unique_together = (('date', 'source', 'target', 'value', 'description'),)
        ordering = ['-date']

    def __unicode__(self):
        return u'%s' % (self.date)

casevo/accounts/views.py
from django.views.generic import UpdateView, ListView
from django.core.urlresolvers import reverse_lazy

from casevo.accounts.models import Account


class AccountListView(ListView):
    def get_queryset(self):
        return Account.objects.select_related('transactions_out', 'transactions_in').all()


class AccountUpdateView(UpdateView):
    model = Account
    template_name = 'accounts/account_update.html'
    success_url = reverse_lazy('accounts:list')

casevo/common/views.py
from django.views.generic import TemplateView


class CasevoHomeView(TemplateView):
    template_name = "base.html"

casevo/statistics/views.py
from django.views.generic import TemplateView

from casevo.accounts.models import Account


class StatisticHomeView(TemplateView):
    template_name = 'statistics/statistic_home.html'


class StatisticAccountsPieView(TemplateView):
    template_name = 'statistics/statistic_accounts_pie.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticAccountsPieView, self).get_context_data(**kwargs)
        context['accounts_in'] = []
        context['accounts_out'] = []
        context['accounts'] = Account.objects.all()
        for account in context['accounts']:
            if account.balance() > 0:
                context['accounts_in'].append(account)
            else:
                context['accounts_out'].append(account)

        return context

casevo/transactions/views.py
from django.views.generic import ListView

from casevo.transactions.models import Transaction


class TransactionListView(ListView):
    def get_queryset(self):
        return Transaction.objects.select_related().all()

casevo/accounts/templates/accounts/account_list.html
{% extends "base.html" %}

{% load i18n %}


{% block content %}
<div class="page-header">
  <h1>{% trans "Accounts" %} <small>{{account_list.count}}</small></h1>
</div>
<table class="table table-condensed table-hover table-clickable">
  <thead>
    <tr>
      <th>{% trans "Identifier" %}</th>
      <th>{% trans "Number" %}</th>
      <th>{% trans "BLZ" %}</th>
      <th>{% trans "Balance" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for account in account_list %}
    <tr href="{% url 'accounts:update' account.id %}">
      <td>{{account.identifier}}</td>
      <td>{{account.number}}</td>
      <td>{{account.blz}}</td>
      <td>{{account.balance}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function() {
    $('table.table-clickable > tbody > tr').click(function() {
      var href = $(this).attr('href');
      if(href) {
        window.location = href;
      }
    });
  });
</script>
<style type="text/css">
  .table-clickable tr {
    cursor: pointer;
  }
</style>
{% endblock %}

casevo/accounts/templates/accounts/account_update.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap %}


{% block content %}
<div class="page-header">
  <h1>{% trans "Account" %}</h1>
</div>
<form method="post" action="{% url 'accounts:update' account.id %}">
  {% csrf_token %}
  {{form|bootstrap}}
  <input type="submit" class="btn btn-default">
</form>
<h2>Transactions</h2>
<h3>Incoming</h3>
<table class="table table-condensed">
  <tr>
    <th>Date</th>
    <th>Source</th>
    <th>Target</th>
    <th>Value</th>
  </tr>
  {% for transaction in account.transactions_in.all %}
  <tr>
    <td>{{transaction.date}}</td>
    <td>{{transaction.source}}</td>
    <td>{{transaction.target}}</td>
    <td>{{transaction.value}}</td>
  </tr>
  {% endfor %}
</table>
<h3>Outgoing</h3>
<table class="table table-condensed">
  <tr>
    <th>Date</th>
    <th>Source</th>
    <th>Target</th>
    <th>Value</th>
  </tr>
  {% for transaction in account.transactions_out.all %}
  <tr>
    <td>{{transaction.date}}</td>
    <td>{{transaction.source}}</td>
    <td>{{transaction.target}}</td>
    <td>{{transaction.value}}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

casevo/common/templates/base.html
{% load i18n %}
{% load bootstrapnavtags %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}casevo{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">casevo</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% navitem 'Accounts' 'accounts:list' %}
            {% navitem 'Transactions' 'transactions:list' %}
            {% navitem 'Statistics' 'statistics:home' %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container" style="margin-top: 60px;">
      {% block content %}
      <h1>Hello, world!</h1>
      {% endblock %}
    </div>
    <script src="{{STATIC_URL}}js/jquery-2.0.3.min.js"></script>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    {% block js %}{% endblock %}
  </body>
</html>

casevo/statistics/templates/statistics/statistic_accounts_pie.html
{% extends "base.html" %}

{% load i18n %}


{% block content %}
<div class="page-header">
  <h1>{% trans "Statistics" %} <small>{% trans "Accounts pie chart" %}</h1>
</div>
<div id="flot-container" style="height: 500px;"></div>
{% endblock %}


{% block js %}
<script src="{{STATIC_URL}}js/jquery.flot.min.js"></script>
<script src="{{STATIC_URL}}js/jquery.flot.pie.min.js"></script>
<script>
  function labelFormatter(label, series) {
    return "<div style='font-size:8pt; text-align:center; padding:2px; color:#000;'>" + label + "<br/>" + Math.round(series.percent) + "%</div>";
  }

  $(document).ready(function() {
    var data = [];
    var counter = 0;

    {% for account in accounts_out %}
    data.push({
      label: "{{account.identifier|truncatechars:15}}",
      data: {{account.balance}}
    });
    {% endfor %}

    var placeholder = $('#flot-container');

    $.plot(placeholder, data, {
      series: {
        pie: {
          show: true,
          radius: 0.75,
          innerRadius: 0,
          label: {
            show: true,
            radius: 1,
            formatter: labelFormatter,
            background: {
              opacity: 0.5,
            },
          },
          combine: {
            color: '#999',
            threshold: 0.01
          }
        }
      },
      legend: {
        show: false
      }
    });
  });
</script>
{% endblock %}

casevo/statistics/templates/statistics/statistic_home.html
{% extends "base.html" %}

{% load i18n %}


{% block content %}
<div class="page-header">
  <h1>{% trans "Statistics" %}</h1>
</div>
<h2>{% trans "Accounts" %}</h2>
<ul class="nav nav-pills">
  <li><a href="{% url 'statistics:accounts-pie' %}">{% trans "Accounts pie" %}</a></li>
</ul>
{% endblock %}

casevo/transactions/templates/transactions/transaction_list.html
{% extends "base.html" %}

{% load i18n %}


{% block content %}
<div class="page-header">
  <h1>{% trans "Transactions" %} <small>{{transaction_list.count}}</small></h1>
</div>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>{% trans "Date" %}</th>
      <th>{% trans "Source" %}</th>
      <th>{% trans "Target" %}</th>
      <th>{% trans "Value" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transaction_list %}
    <tr>
      <td>{{transaction.date}}</td>
      <td>{{transaction.source}}</td>
      <td>{{transaction.target}}</td>
      <td{% if transaction.value < 0 %} style="color: red;"{% endif %}>{{transaction.value|floatformat:2}} {{transaction.target.currency}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}